version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3055:3055"
    env_file:
      - ./backend/.env
    environment:
      - PORT=3055
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    command: npx ts-node src/index.ts

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3737:3737"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3055
    env_file:
      - ./frontend/.env.local
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev
    depends_on:
      - backend
